app:
  cache:
    name: TCCache10

#  How to create a FS persistable H2 DB
#  spring.datasource.url: jdbc:h2:file:/data/demo

spring:
  datasource:
  url: jdbc:h2:mem:testdb
  driverClassName: org.h2.Driver
  username: sa
  password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true
